name: gomuks-android

env:
  main_project_module: net.vrkknn.gomuks
  playstore_name: gomuks

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew assemble --stacktrace
    
    - name: Upload missing rules
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: r8-missing-rules
        path: app/build/outputs/mapping/release/missing_rules.txt

    - name: List APKs
      run: |
        echo "### Built APKs" >> $GITHUB_STEP_SUMMARY
        find app/ -name "*.apk" | tee -a $GITHUB_STEP_SUMMARY

    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: net.vrkknn.gomuks
        path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

    - name: Install gh cli
      run: sudo apt update && sudo apt install gh -y

    - name: Generate tag and release
      id: create_release
      run: |
        TAG_NAME="release-$(date +'%Y%m%d-%H%M%S')"
        gh release create "$TAG_NAME" \
          --title "$TAG_NAME" \
          --notes "Automated release $TAG_NAME"
        echo "release_id=$(gh release view "$TAG_NAME" --json id -q '.id')" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy nightly
      uses: WebFreak001/deploy-nightly@v3.1.0
      with:
        upload_url: ${{ github.api_url }}/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.release_id }}/assets{?name, label}
        release_id: ${{ steps.create_release.outputs.release_id }}
        asset_path: app/build/outputs/apk/release/app-arm64-v8a-release.apk
        asset_name: gomuks.vrkknn.net_release-$(date +'%Y%m%d-%H%M%S').apk
        asset_content_type: application/vnd.android.package-archive
        max_releases: 5
        
